version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0"
    container_name: swapi-graphql
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    ports:
      - 8001:8000
